jobs:

- job: macOS

  timeoutInMinutes: 0

  pool:
    vmImage: 'macOS-10.14'

  strategy:
    matrix:
      Julia 1.2:
        JULIA_VERSION: '1.2'

  steps:
  - bash: |
      set -o xtrace
      wget -nv https://julialang-s3.julialang.org/bin/mac/x64/$(JULIA_VERSION)/julia-$(JULIA_VERSION)-latest-mac64.dmg
      mkdir juliamnt
      hdiutil mount -readonly -mountpoint juliamnt julia-$(JULIA_VERSION)-latest-mac64.dmg
      cp -a juliamnt/*.app/Contents/Resources/julia julia-$(JULIA_VERSION)
    displayName: 'Download and extract Julia'
  - bash: |
      set -o xtrace
      brew update
      brew upgrade
    displayName: 'Install dependencies'
  - bash: |
      set -o xtrace
      ./julia-$(JULIA_VERSION)/bin/julia -e 'using InteractiveUtils; versioninfo()'
      ./julia-$(JULIA_VERSION)/bin/julia --project=@. -e 'using Pkg; Pkg.add("Conda"); using Conda; Conda.add("libnetcdf")'
      ./julia-$(JULIA_VERSION)/bin/julia --project=@. -e 'using Pkg; Pkg.instantiate()'
      ./julia-$(JULIA_VERSION)/bin/julia --project=@. -e 'using Pkg; Pkg.test()'
    displayName: 'Run the tests'

