jobs:
- job: Linux

  timeoutInMinutes: 0

  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      Julia 1.2:
        JULIA_VERSION: '1.2'

  steps:
  - bash: |
      set -o xtrace
      wget -nv https://julialang-s3.julialang.org/bin/linux/x64/$(JULIA_VERSION)/julia-$(JULIA_VERSION)-latest-linux-x86_64.tar.gz
      mkdir julia-$(JULIA_VERSION)
      tar zxf julia-$(JULIA_VERSION)-latest-linux-x86_64.tar.gz -C julia-$(JULIA_VERSION) --strip-components 1
    displayName: 'Download and extract Julia'
  - bash: |
      set -o xtrace
      sudo apt-get update
    displayName: 'Install dependencies'
  - bash: |
      set -o xtrace
      ./julia-$(JULIA_VERSION)/bin/julia -e 'using InteractiveUtils; versioninfo()'
      ./julia-$(JULIA_VERSION)/bin/julia --project=@. -e 'using Pkg; Pkg.instantiate()'
      ./julia-$(JULIA_VERSION)/bin/julia --project=@. -e 'using Pkg; Pkg.test(coverage=true)'
    displayName: 'Run the tests'
  - bash: |
      ./julia-$(JULIA_VERSION)/bin/julia --project=.coverage -e 'using Pkg; Pkg.instantiate();
                                                                 Pkg.add("Coverage");
                                                                 using Coverage;
                                                                 Codecov.submit_local(Codecov.process_folder();
                                                                   service = "azure_pipelines",
                                                                   commit       = @show(ENV["BUILD_SOURCEVERSION"]),
                                                                   pull_request = @show(get(ENV, "SYSTEM_PULLREQUEST_PULLREQUESTNUMBER", "false")),
                                                                   job          = @show(ENV["BUILD_DEFINITIONNAME"]),
                                                                   slug         = @show(ENV["BUILD_REPOSITORY_NAME"]),
                                                                   build        = @show(ENV["BUILD_BUILDID"]))'
    env:
      CODECOV_TOKEN: "e62dc66d-04f1-424f-9c4d-1278fa8b2e8d"
    displayName: 'Submit code coverage'

