ignore:
  - "src/examples/rfmip-clear-sky/rrtmgp_rfmip_lw.jl"
  - "/Users/charliekawczynski/Dropbox/Caltech/work/dev/JRRTMGP/src/rrtmgp/kernels-openacc/mo_gas_optics_kernels.jl"
  - "/Users/charliekawczynski/Dropbox/Caltech/work/dev/JRRTMGP/src/extensions/cloud_optics/mo_cloud_optics.jl"
  - "/Users/charliekawczynski/Dropbox/Caltech/work/dev/JRRTMGP/src/extensions/cloud_optics/mo_cloud_sampling.jl"
  - "/Users/charliekawczynski/Dropbox/Caltech/work/dev/JRRTMGP/src/extensions/mo_compute_bc.jl"
  - "/Users/charliekawczynski/Dropbox/Caltech/work/dev/JRRTMGP/src/extensions/mo_fluxes_bygpoint.jl"
  - "/Users/charliekawczynski/Dropbox/Caltech/work/dev/JRRTMGP/src/extensions/mo_heating_rates.jl"
  - "/Users/charliekawczynski/Dropbox/Caltech/work/dev/JRRTMGP/src/extensions/mo_rrtmgp_clr_all_sky.jl"
  - "/Users/charliekawczynski/Dropbox/Caltech/work/dev/JRRTMGP/src/rte/kernels-openacc/mo_optical_props_kernels.jl"
  - "/Users/charliekawczynski/Dropbox/Caltech/work/dev/JRRTMGP/src/rte/kernels-openacc/mo_rte_solver_kernels.jl"
  - "/Users/charliekawczynski/Dropbox/Caltech/work/dev/JRRTMGP/src/rte/mo_rte_kind.jl"
  - "/Users/charliekawczynski/Dropbox/Caltech/work/dev/JRRTMGP/src/rte/mo_rte_lw.jl"
