steps:
  - label: "run unit tests CPU"
    command: "julia --color=yes --project test/runtests.jl"
    agents:
      config: cpu 
      queue: central
      slurm_ntasks: 1
      slurm_mem-per-cpu: 5G  
  - label: "run units tests GPU"
    command: "julia --color=yes --project test/runtests_gpu.jl"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"
  
