env:
  JULIA_VERSION: "1.6.0"
  CUDA_VERSION: "11.2"

steps:
  - label: "run unit tests CPU"
    command:
      - "julia --color=yes --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --color=yes --project test/runtests.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1
      slurm_mem_per_cpu: 6G

  - label: "run units tests GPU"
    command:
      - "julia --color=yes --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --color=yes --project test/runtests_gpu.jl"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"
