agents:
  queue: new-central
  modules: climacommon/2024_02_20
  partition: expansion

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  JULIA_CPU_TARGET: 'broadwell;skylake;icelake;cascadelake;epyc'
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100

steps:
  - label: "init cpu environments :computer:"
    key: "init_cpu_env"
    command:

      - echo "--- Instantiate examples environment"
      - "julia --project=examples -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

  - label: "init gpu environments :computer:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate gpu environment"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_gres: "gpu:1"
      partition: gpu

  - wait

  - group: "Unit tests"
    steps:

      - label: "CPU unit tests"
        command: "julia --color=yes --project=examples test/runtests.jl"
        agents:
          slurm_mem_per_cpu: 6G

      - label: "Threaded CPU unit tests"
        command: "julia --threads 8 --color=yes --project=examples test/runtests.jl"
        agents:
          slurm_cpus_per_task: 8
          slurm_mem_per_cpu: 6G

      - label: "GPU unit tests"
        command: "julia --color=yes --project=gpuenv test/runtests_gpu.jl"
        agents:
          slurm_gres: "gpu:1"
          partition: gpu

  - group: "Flame graphs"
    steps:

      - label: "Flame Graph: Gray Atm"
        command: "julia --color=yes --project=examples perf/flame.jl gray_atm.jl"
        artifact_paths: "flame_graphs/gray_atm/*"
        agents:
          slurm_mem_per_cpu: 6G

      - label: "Flame Graph: Clear Sky"
        command: "julia --color=yes --project=examples perf/flame.jl clear_sky.jl"
        artifact_paths: "flame_graphs/clear_sky/*"
        agents:
          slurm_mem_per_cpu: 6G

      - label: "Flame Graph: All Sky"
        command: "julia --color=yes --project=examples perf/flame.jl all_sky.jl"
        artifact_paths: "flame_graphs/all_sky/*"
        agents:
          slurm_mem_per_cpu: 6G

  - group: "Benchmarks"
    steps:

      - label: "Benchmarks"
        command: "julia --color=yes --project=examples perf/benchmark.jl"
        agents:
          slurm_mem_per_cpu: 6G

      - label: "Benchmarks (Float32)"
        command: "julia --color=yes --project=examples perf/benchmark.jl Float32"
        agents:
          slurm_mem_per_cpu: 6G

      - label: "Threaded benchmarks"
        command: "julia --threads=8 --color=yes --project=examples perf/benchmark.jl"
        agents:
          slurm_cpus_per_task: 8
          slurm_mem_per_cpu: 6G

      - label: "GPU benchmarks"
        command: "julia --color=yes --project=gpuenv perf/benchmark.jl"
        agents:
          slurm_gres: "gpu:1"
          partition: gpu

      - label: "GPU All-sky DYAMOND benchmark"
        command: "julia --color=yes --project=gpuenv test/all_sky_dyamond_gpu_benchmark.jl"
        agents:
          slurm_gres: "gpu:1"
          partition: gpu
