agents:
  queue: central
  slurm_mem: 8G
  modules: julia/1.8.5 cuda/11.8 ucx/1.14.1_cuda-11.8 openmpi/4.1.5_cuda-11.8

env:
  JULIA_VERSION: "1.8.5"
  CUDA_VERSION: "11.2"

steps:
  - label: "init cpu environments :computer:"
    key: "init_cpu_env"
    command:

      - echo "--- Configure MPI"
      - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate examples environment"
      - "julia --project=examples -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1
    #   slurm_cpus_per_task: 8
    # env:
    #   JULIA_NUM_PRECOMPILE_TASKS: 8

  - label: "init gpu environments :computer:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate gpu environment"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.status()'"

    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"
    #   slurm_cpus_per_task: 8
    # env:
    #   JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Unit tests"
    steps:

      - label: "CPU unit tests"
        command: "julia --color=yes --project=examples test/runtests.jl"
        agents:
          config: cpu
          queue: central
          slurm_ntasks: 1
          slurm_mem_per_cpu: 6G

      - label: "Threaded CPU unit tests"
        command: "julia --threads 8 --color=yes --project=examples test/runtests.jl"
        agents:
          config: cpu
          queue: central
          slurm_cpus_per_task: 8
          slurm_mem_per_cpu: 6G

      - label: "GPU unit tests"
        command: "julia --color=yes --project=gpuenv test/runtests_gpu.jl"
        agents:
          config: gpu
          queue: central
          slurm_ntasks: 1
          slurm_gres: "gpu:1"
