env:
  JULIA_VERSION: "1.8.5"
  CUDA_VERSION: "11.2"

steps:
  - label: "init cpu environments :computer:"
    key: "init_cpu_env"
    command:

      - echo "--- Instantiate examples environment"
      - "julia --project=examples -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=examples -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=examples -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=examples -e 'using Pkg; Pkg.status()'"

    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1
    #   slurm_cpus_per_task: 8
    # env:
    #   JULIA_NUM_PRECOMPILE_TASKS: 8

  - label: "init gpu environments :computer:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate gpu environment"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=gpuenv -e 'using Pkg; Pkg.status()'"

    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"
    #   slurm_cpus_per_task: 8
    # env:
    #   JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Unit tests"
    steps:

      - label: "CPU unit tests"
        command: "julia --color=yes --project=examples test/runtests.jl"
        agents:
          config: cpu
          queue: central
          slurm_ntasks: 1
          slurm_mem_per_cpu: 6G

      - label: "Threaded CPU unit tests"
        command: "julia --threads 8 --color=yes --project=examples test/runtests.jl"
        agents:
          config: cpu
          queue: central
          slurm_cpus_per_task: 8
          slurm_mem_per_cpu: 6G

      - label: "GPU unit tests"
        command: "julia --color=yes --project=gpuenv test/runtests_gpu.jl"
        agents:
          config: gpu
          queue: central
          slurm_ntasks: 1
          slurm_gres: "gpu:1"

  - group: "Flame graphs"
    steps:

      - label: "Flame Graph: Gray Atm"
        command: "julia --color=yes --project=examples perf/flame.jl gray_atm.jl"
        artifact_paths: "flame_graphs/gray_atm/*"
        agents:
          config: cpu
          queue: central
          slurm_ntasks: 1
          slurm_mem_per_cpu: 6G

      - label: "Flame Graph: Clear Sky"
        command: "julia --color=yes --project=examples perf/flame.jl clear_sky.jl"
        artifact_paths: "flame_graphs/clear_sky/*"
        agents:
          config: cpu
          queue: central
          slurm_ntasks: 1
          slurm_mem_per_cpu: 6G

      - label: "Flame Graph: All Sky"
        command: "julia --color=yes --project=examples perf/flame.jl all_sky.jl"
        artifact_paths: "flame_graphs/all_sky/*"
        agents:
          config: cpu
          queue: central
          slurm_ntasks: 1
          slurm_mem_per_cpu: 6G

  - group: "Benchmarks"
    steps:
  
      - label: "Benchmarks"
        command: "julia --color=yes --project=examples perf/benchmark.jl"
        agents:
          config: cpu
          queue: central
          slurm_ntasks: 1
          slurm_mem_per_cpu: 6G

      - label: "Threaded benchmarks"
        command: "julia --threads=8 --color=yes --project=examples perf/benchmark.jl"
        agents:
          config: cpu
          queue: central
          slurm_cpus_per_task: 8
          slurm_mem_per_cpu: 6G
