#####
##### The public API
#####
#
# Names listed here change only with the package version; anything else
# (submodule internals, buffer layouts, names prefixed with `_`) may change in a
# patch release. `test/public_api.jl` locks the list. `public` needs Julia 1.11;
# below that the list and the test still hold.

const PUBLIC_NAMES = (
    # Configuration and construction
    :AbstractRRTMGPMethod,
    :RRTMGPGridParams,
    :RRTMGPSolver,
    :GrayRadiation,
    :ClearSkyRadiation,
    :AllSkyRadiation,
    :AllSkyRadiationWithClearSkyDiagnostics,
    :radiation_method,
    :isothermal_boundary_layer,
    :default_parameters,
    # Lookup tables
    :lookup_tables,
    :LookupBundle,
    :save_lookup_tables,
    :load_lookup_tables,
    :gas_names_sw,
    # Aerosol species naming
    :aerosol_names,
    :aerosol_index,
    :aerosol_index_map,
    :canonical_aerosol_name,
    # Level interpolation and grid adaptation
    :AbstractInterpolation,
    :NoInterpolation,
    :ArithmeticMean,
    :GeometricMean,
    :UniformZ,
    :UniformP,
    :BestFit,
    :AbstractBottomExtrapolation,
    :SameAsInterpolation,
    :UseSurfaceTempAtBottom,
    :HydrostaticBottom,
    :requires_z,
    :interp!,
    :extrap!,
    :uniform_z_p,
    :best_fit_p,
    :interpolate_levels!,
    :add_isothermal_boundary_layer!,
    :clip!,
    :update_concentrations!,
    :get_p_min,
    :get_t_min,
    :get_t_max,
    # Running a solve
    :prepare_atmosphere!,
    :update_fluxes!,
    :update_lw_fluxes!,
    :update_sw_fluxes!,
    :update_net_fluxes!,
    :check_values,
    :validate_inputs,
    # State getters (inputs)
    :layer_pressure,
    :layer_temperature,
    :layer_relative_humidity,
    :level_pressure,
    :level_temperature,
    :surface_temperature,
    :surface_emissivity,
    :latitude,
    :center_z,
    :face_z,
    :cos_zenith,
    :toa_sw_flux_dn,
    :toa_diffuse_sw_flux_dn,
    :toa_lw_flux_dn,
    :direct_sw_surface_albedo,
    :diffuse_sw_surface_albedo,
    :volume_mixing_ratio,
    :set_volume_mixing_ratio!,
    :cloud_liquid_effective_radius,
    :cloud_ice_effective_radius,
    :cloud_liquid_water_path,
    :cloud_ice_water_path,
    :cloud_fraction,
    :aerosol_column_mass_density,
    :aerosol_radius,
    :optical_thickness_parameter,
    :deep_atmosphere_inverse_scaling,
    # Flux and diagnostic getters (outputs)
    :lw_flux_up,
    :lw_flux_dn,
    :lw_flux_net,
    :sw_flux_up,
    :sw_flux_dn,
    :sw_flux_net,
    :sw_direct_flux_dn,
    :net_flux,
    :clear_lw_flux_up,
    :clear_lw_flux_dn,
    :clear_lw_flux_net,
    :clear_sw_flux_up,
    :clear_sw_flux_dn,
    :clear_sw_direct_flux_dn,
    :clear_sw_flux_net,
    :clear_net_flux,
    :heating_rate,
    :lw_cloud_cover,
    :sw_cloud_cover,
    :aod_sw_extinction,
    :aod_sw_scattering,
    :spectral_lw_flux_up,
    :spectral_lw_flux_dn,
    :spectral_lw_flux_net,
    :spectral_sw_flux_up,
    :spectral_sw_flux_dn,
    :spectral_sw_flux_net,
    :lw_band_bounds,
    :sw_band_bounds,
    # Standalone entry points
    :AtmosphereProfile,
    :standard_atmosphere,
    :solve,
    :solve_gray,
    :RadiationOutput,
)

@static if VERSION >= v"1.11"
    eval(Expr(:public, PUBLIC_NAMES...))
end
